### PR TITLE
Disable dependency checks if no compatibility is intended

### PR DESCRIPTION
**Pull request by julienrf**

### CODE REVIEW

**Comment by sjrd** [comment]
Isn't that a bit "dangerous"? If the user forgets to specify `versionPolicyIntention`, or puts it in the wrong scope or something, then the checks will be silently ignored rather than loudly fail.

**Comment by julienrf** [comment]
The check won’t be skipped if the user forgets to specify `versionPolicyIntention`. It will be skipped only if he explicitly sets it to `Compatibility.None`.

The motivation is the following. Let’s say we have a library. We release the version `1.0.0`. We start working on the next major version (will be `2.0.0`), and we break binary compatibility. We set `versionPolicyIntention := Compatibility.None`. However, `versionPolicyCheck` may fail because of its subtask `versionPolicyReportDependencyIssues`. Why? A common (?) practice is to rely on `sbt-ci-release` to compute the version of the library. Until we actually push the Git tag to cut the release, the version will be something like `1.0.0+42-abcd1234`, which will make the task `versionPolicyReportDependencyIssues` fail because it does not start by `2.0.0`. Note that the task `versionPolicyMimaCheck` is already skipped in case `versionPolicyIntention` is `Compatibility.None`.

An alternative way to solve this issue would be to completely change our habits, and instead of relying on Git tags/commits to set the version, we would ask developers to manually set their version number in their build. With this change, we could even get rid of the setting `versionPolicyIntention` because we could compute its value from the version set in the build.

**Comment by sjrd** [comment]
Hum I see. That is indeed necessary for git-based version numbering.

But for those of us who do write the version numbers in the build file, we'll lose some checks here. I'd like my build to complain if `version := "1.2.0-SNAPSHOT"` but I have `versionPolicyIntention := None`.

Could we somehow reconcile this?

**Comment by julienrf** [comment]
> But for those of us who do write the version numbers in the build file, we'll lose some checks here. I'd like my build to complain if `version := "1.2.0-SNAPSHOT"` but I have `versionPolicyIntention := None`.
> 
> Could we somehow reconcile this?

The solution I propose is to have two checks.

1. During development (e.g., validation of PRs) you run `versionPolicyCheck`, which checks that binary compatibility is consistent with `versionPolicyIntention` (but it does not really rely on `version`)
2. When you actually want to cut a release, you run `versionCheck`, which checks that `version` is consistent with `versionPolicy`. You would get a failure if you run this task and you have `version := "1.2.0-SNAPSHOT` and `versionPolicyIntention := None`.

**Comment by sjrd** [comment]
I guess it's good enough. We'll just have to remember to change `version` and `versionPolicyIntention` at the same time.

**Comment by sjrd** [comment]
What does this PR do when
* `versionPolicyIntention := Compatibility.BinaryCompatible`
* `version` is computed to be `1.2.4+whatever`
* I introduce a source-incompatible change that is planned for 1.3.0

?

**Comment by julienrf** [comment]
This PR changes nothing in this case.

Running `versionPolicyCheck` will succeed because MiMa will check for binary incompatibilities only (based on `versionPolicyIntention`), and the dependency check will also succeed (assuming you didn’t bump your dependencies to a new major version).

Running `versionCheck` will fail because the patch number is not 0.

**Review by sjrd — APPROVED** [review]

**Pull request merged**
